### ISSUE TITLE
[Bug] static navbar missing part in bottom

### ISSUE THREAD

**Issue by Grovkillen** [mubaidr/bulma-addons#6]
![screenshot_20180605-113114](https://user-images.githubusercontent.com/26706274/40967814-57ee0fda-68b4-11e8-9dfc-a502ce85466f.jpg)
![screenshot_20180605-104612](https://user-images.githubusercontent.com/26706274/40967826-60b7e6a4-68b4-11e8-9df2-8dd1936b1c99.jpg)

As seen in the screenshots. It looks good in Chrome on desktop but on mobile a bit if missing.

**Comment by Grovkillen** [comment]
Also, the single column on mobile will make a trench appear on the b right. It looks good on desktop where the columns is displayed next to each other, whereas on mobile the column is displayed on top of each other.

**Comment by mubaidr** [comment]
- The navigation bug had this bug in earlier version. Please use the latest version. here is the demo: 
https://codepen.io/mubaidr/pen/gKPOZR?editors=1000

- I am testing the columns issue on mobile.

**Comment by Grovkillen** [comment]
I updated to latest but the bug is still there. I think it has to do with the trench/gap to the right of the column since the zoom out cause the bug to appear.

**Comment by Grovkillen** [comment]
Latest version introduce this problem where the navbar is not possible to scroll all the way down:
![image 1](https://user-images.githubusercontent.com/26706274/40976171-83c1bbd4-68cd-11e8-90c8-f72ca09f31d3.png)

**Comment by mubaidr** [comment]
Navigation scroll issue is confirmed. Working on the fix.

**Comment by mubaidr** [comment]
Please can you provide some code sample, maybe jsfiddle or codepen to replicate this issue?

**Comment by Grovkillen** [comment]
I updated to latest version and both bugs are gone! Thanks!

**Comment by mubaidr** [comment]
Awesome!
